spring:
  application:
    name: notificationms
  datasource:
    url: 'jdbc:postgresql://localhost:8906/postgres'
    username: postgres
    password: Krsna@123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_schema: microservice_project
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
server:
  port: 8766